name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
jobs:
  activate:
    if: "!endsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Proceed
      run: echo ok go
  lint:
    needs: activate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Configure Bundler
      run: |
        bundle config --local path .bundle/gems
        bundle config --local without coverage docs
    - name: Install dependencies
      run: bundle --jobs 3 --retry 3
    - name: Run linter
      run: bundle exec rake lint
  build:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby: [jruby-9.2, '2.5', '2.6', '2.7', '3.0']
        upstream: [~]
        exclude:
        - os: ubuntu-latest
          ruby: '3.0'
        include:
        - os: macos-latest
          ruby: '3.0'
        - os: ubuntu-latest
          ruby: '2.5'
          rouge-version: '~> 2.0.0'
        - os: ubuntu-latest
          ruby: '3.0'
          upstream: upstream
        - os: ubuntu-latest
          ruby: '3.0'
          primary: primary
    runs-on: ${{ matrix.os }}
    env:
      MENTOS_TIMEOUT: 30 # give pygments.rb calls more time to execute (in seconds)
      PYGMENTS_VERSION: '~> 1.2.0' # test runner will automatically disable Pygments tests on JRuby for Windows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Reinstall Bundler
      if: matrix.os == 'windows-latest' && matrix.ruby == 'jruby-9.2'
      run: |
        gem uninstall -x bundler
        gem install -N bundler -v 2.1.4
    - name: Configure Bundler
      run: |
        bundle config --local path .bundle/gems
        bundle config --local without coverage docs lint
    - name: Set Rghost version / Install Ghostscript (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo 'RGHOST_VERSION=0.9.7' >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install ghostscript poppler-utils
    - name: Install Ghostscript and Poppler (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install ghostscript poppler
    - name: Set Prawn Gmagick version / Install GraphicsMagick (Linux only)
      if: matrix.primary
      run: |
        echo 'PRAWN_GMAGICK_VERSION=0.0.9' >> $GITHUB_ENV
        sudo apt-get install libgraphicsmagick1-dev
    - name: Set Asciidoctor version override
      if: matrix.asciidoctor-version
      run: echo 'ASCIIDOCTOR_VERSION=${{ matrix.asciidoctor-version }}' >> $GITHUB_ENV
      shell: bash
    - name: Install dependencies
      run: bundle --jobs 3 --retry 3
    - name: Switch to upstream dependencies
      if: matrix.upstream
      run: |
        bundle exec ruby scripts/switch-to-prawn-master.rb
        rm -f Gemfile.lock
        bundle config --local clean true
        bundle --jobs 3 --retry 3
    - name: Run tests
      run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(rake)') spec
